# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortenerapp', '0003_auto_20171127_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdatetime', models.DateTimeField(auto_now_add=True, db_column='visited_datetime')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urlshortenerapp.Url')),
            ],
            options={
                'db_table': 'url_visit',
            },
        ),
    ]
